### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by dtran26** [jeantimex/CollapsibleTableSectionViewController#44]
Hi,

When I pod install I get the message '[!] Unable to find a specification for `CollapsibleTableSectionViewController`'

Thanks

**Comment by mohanmoorthy** [comment]
yep.. same issue. @jeantimex  can you please look at it ?

**Comment by jeantimex** [comment]
Sure, let me take a look, thanks for let me know!

**Comment by jeantimex** [comment]
Hi @dtran26, @mohanmoorthy, I think I may have found the root cause for you, if you are using Cocoapods 1.0.0 or above, `pod repo update` does not happen on `pod install` by default, that means you have to run `pod repo update` manually to update the repo source list on your machine.

After you run `pod repo update`, try `pod search CollapsibleTableSectionViewController`, you should see the latest version of the pod is 1.0.1. Then you can do `pod install`. Or try `pod install --repo-update`. (note, pod repo indexing may take a bit of time)

Below is my screenshot:
<img width="1437" alt="screen shot 2017-08-04 at 8 18 36 am" src="https://user-images.githubusercontent.com/565300/28975087-998143de-78ed-11e7-83c7-fbc5b4a80584.png">

**Comment by dtran26** [comment]
Thanks it works after updating repo source list!

**Comment by jeantimex** [comment]
Thanks @dtran26! How about you @mohanmoorthy?
